function cvArray = create_cv_array(M,N)
    % cvArray = struct('methodName', repmat({[]}, M, N), ...
    %     'model', [], ... %'XtSample',[],...
    %     'evalParams',[], 'tuneTime', [], ...
    %     'trainTime',[], 'sampleTime',[],'evalMetricValues',[]);
    cvArray = struct('methodName', repmat({[]}, M, N), ...
        'model', [], 'evalParams', [], 'timing', [], 'evalMetricValues', []);
